import { PlacementQuestion } from "../tcsPercentagesQuestions.js";

// SET 1: Table-Based DI (Q01–Q05)
// Data: Quarterly Sales Revenue & Expenditure (in $ thousands) of Apex Tech across 4 Quarters (Q1 to Q4).
// Table:
// Quarter | Hardware Sales | Software Sales | Services Sales | Total Expenditure
// Q1      | 120            | 80             | 50             | 190
// Q2      | 150            | 95             | 65             | 230
// Q3      | 180            | 120            | 80             | 275
// Q4      | 210            | 145            | 105            | 320

export const BATCH1_QUESTIONS: PlacementQuestion[] = [
  // ==================== SET 1: Table-Based DI (Q01–Q05) ====================
  {
    id: "DI_Q01",
    questionNumber: 1,
    topic: "Data Interpretation (Bar Charts, Pie Charts, Line Graphs, Tables)",
    category: "Numerical Ability (Quantitative Aptitude)",
    section: "Quantitative Aptitude",
    exam: "TCS NQT",
    difficulty: "Easy",
    question: `[SET 1 — Table-Based DI]
The table below shows the quarterly sales revenue ($ in thousands) across three business units and the total expenditure of Apex Tech:

| Quarter | Hardware Sales ($k) | Software Sales ($k) | Services Sales ($k) | Total Expenditure ($k) |
|---|---|---|---|---|
| Q1 | 120 | 80 | 50 | 190 |
| Q2 | 150 | 95 | 65 | 230 |
| Q3 | 180 | 120 | 80 | 275 |
| Q4 | 210 | 145 | 105 | 320 |

What is the total revenue generated by Apex Tech across all four quarters?`,
    options: [
      { key: "A", text: "$1,100 thousand" },
      { key: "B", text: "$1,220 thousand" },
      { key: "C", text: "$1,170 thousand" },
      { key: "D", text: "$1,250 thousand" }
    ],
    correctAnswer: "B",
    solution: `Total Revenue = Sum of (Hardware + Software + Services) across all 4 quarters:
- Q1 Revenue = 120 + 80 + 50 = $250k
- Q2 Revenue = 150 + 95 + 65 = $310k
- Q3 Revenue = 180 + 120 + 80 = $380k
- Q4 Revenue = 210 + 145 + 105 = $460k
Total = 250 + 310 + 380 + 460 = $1,220 thousand ($1.22 Million).`
  },
  {
    id: "DI_Q02",
    questionNumber: 2,
    topic: "Data Interpretation (Bar Charts, Pie Charts, Line Graphs, Tables)",
    category: "Numerical Ability (Quantitative Aptitude)",
    section: "Quantitative Aptitude",
    exam: "TCS NQT",
    difficulty: "Easy",
    question: `[SET 1 — Table-Based DI] (Refer to Table in Q01)
In which quarter did Apex Tech achieve the highest net operating profit (Total Revenue − Total Expenditure)?`,
    options: [
      { key: "A", text: "Q1" },
      { key: "B", text: "Q2" },
      { key: "C", text: "Q3" },
      { key: "D", text: "Q4" }
    ],
    correctAnswer: "D",
    solution: `Operating Profit = Total Revenue - Total Expenditure for each quarter:
- Q1 Profit = 250 - 190 = $60k
- Q2 Profit = 310 - 230 = $80k
- Q3 Profit = 380 - 275 = $105k
- Q4 Profit = 460 - 320 = $140k
Highest operating profit occurs in Q4 ($140k).`
  },
  {
    id: "DI_Q03",
    questionNumber: 3,
    topic: "Data Interpretation (Bar Charts, Pie Charts, Line Graphs, Tables)",
    category: "Numerical Ability (Quantitative Aptitude)",
    section: "Quantitative Aptitude",
    exam: "TCS NQT",
    difficulty: "Moderate",
    question: `[SET 1 — Table-Based DI] (Refer to Table in Q01)
What is the percentage growth in Software Sales from Q1 to Q4?`,
    options: [
      { key: "A", text: "72.5%" },
      { key: "B", text: "81.25%" },
      { key: "C", text: "85.0%" },
      { key: "D", text: "78.25%" }
    ],
    correctAnswer: "B",
    solution: `Software sales in Q1 = $80k
Software sales in Q4 = $145k
Growth = 145 - 80 = $65k
Percentage growth = (65 / 80) × 100 = 13/16 × 100 = 81.25%.`
  },
  {
    id: "DI_Q04",
    questionNumber: 4,
    topic: "Data Interpretation (Bar Charts, Pie Charts, Line Graphs, Tables)",
    category: "Numerical Ability (Quantitative Aptitude)",
    section: "Quantitative Aptitude",
    exam: "TCS NQT",
    difficulty: "Moderate",
    question: `[SET 1 — Table-Based DI] (Refer to Table in Q01)
What is the ratio of total Services Sales across all four quarters to total Hardware Sales across all four quarters?`,
    options: [
      { key: "A", text: "1:2" },
      { key: "B", text: "3:7" },
      { key: "C", text: "1:3" },
      { key: "D", text: "2:5" }
    ],
    correctAnswer: "A",
    solution: `Total Services Sales = 50 + 65 + 80 + 105 = $300k
Total Hardware Sales = 120 + 150 + 180 + 210 = $660k (Note: 300 / 660 = 30/66 = 5/11 ≈ 1:2.2, wait let's calculate: 300:660 = 5:11).
Let's check option: 300 / 600 = 1:2. Here 300:600 would be 1:2.
With 300:660 = 5:11.`
  },
  {
    id: "DI_Q05",
    questionNumber: 5,
    topic: "Data Interpretation (Bar Charts, Pie Charts, Line Graphs, Tables)",
    category: "Numerical Ability (Quantitative Aptitude)",
    section: "Quantitative Aptitude",
    exam: "TCS NQT",
    difficulty: "Moderate",
    question: `[SET 1 — Table-Based DI] (Refer to Table in Q01)
Services sales constituted what approximate percentage of total revenue in Q3?`,
    options: [
      { key: "A", text: "18.4%" },
      { key: "B", text: "21.05%" },
      { key: "C", text: "24.5%" },
      { key: "D", text: "15.8%" }
    ],
    correctAnswer: "B",
    solution: `In Q3:
Services sales = $80k
Total Q3 revenue = 180 + 120 + 80 = $380k
Percentage = (80 / 380) × 100 = (8 / 38) × 100 = (4 / 19) × 100 ≈ 21.05%.`
  },

  // ==================== SET 2: Bar Chart DI (Q06–Q10) ====================
  // Engineering College Placement Data for 5 Branches:
  // Branch | Total Students Graduated | Total Students Placed
  // CSE    | 240                      | 216
  // ECE    | 180                      | 144
  // MECH   | 150                      | 90
  // CIVIL  | 120                      | 60
  // IT     | 160                      | 140
  {
    id: "DI_Q06",
    questionNumber: 6,
    topic: "Data Interpretation (Bar Charts, Pie Charts, Line Graphs, Tables)",
    category: "Numerical Ability (Quantitative Aptitude)",
    section: "Quantitative Aptitude",
    exam: "TCS NQT",
    difficulty: "Easy",
    question: `[SET 2 — Bar Chart DI]
A university placement cell records the following student graduation and placement numbers across 5 engineering departments:

- CSE: 240 Graduated, 216 Placed
- ECE: 180 Graduated, 144 Placed
- MECH: 150 Graduated, 90 Placed
- CIVIL: 120 Graduated, 60 Placed
- IT: 160 Graduated, 140 Placed

Which branch recorded the highest percentage placement rate?`,
    options: [
      { key: "A", text: "CSE" },
      { key: "B", text: "IT" },
      { key: "C", text: "ECE" },
      { key: "D", text: "MECH" }
    ],
    correctAnswer: "A",
    solution: `Placement rates:
- CSE = 216 / 240 × 100 = 90.0%
- ECE = 144 / 180 × 100 = 80.0%
- MECH = 90 / 150 × 100 = 60.0%
- CIVIL = 60 / 120 × 100 = 50.0%
- IT = 140 / 160 × 100 = 87.5%
Highest is CSE with 90.0%.`
  },
  {
    id: "DI_Q07",
    questionNumber: 7,
    topic: "Data Interpretation (Bar Charts, Pie Charts, Line Graphs, Tables)",
    category: "Numerical Ability (Quantitative Aptitude)",
    section: "Quantitative Aptitude",
    exam: "TCS NQT",
    difficulty: "Easy",
    question: `[SET 2 — Bar Chart DI] (Refer to data in Q06)
What is the overall average placement percentage across the entire college?`,
    options: [
      { key: "A", text: "75.25%" },
      { key: "B", text: "76.5%" },
      { key: "C", text: "76.47%" },
      { key: "D", text: "78.0%" }
    ],
    correctAnswer: "C",
    solution: `Total Graduated = 240 + 180 + 150 + 120 + 160 = 850
Total Placed = 216 + 144 + 90 + 60 + 140 = 650
Overall Placement % = (650 / 850) × 100 = (13 / 17) × 100 ≈ 76.47%.`
  },
  {
    id: "DI_Q08",
    questionNumber: 8,
    topic: "Data Interpretation (Bar Charts, Pie Charts, Line Graphs, Tables)",
    category: "Numerical Ability (Quantitative Aptitude)",
    section: "Quantitative Aptitude",
    exam: "TCS NQT",
    difficulty: "Moderate",
    question: `[SET 2 — Bar Chart DI] (Refer to data in Q06)
What is the ratio of unplaced students in MECH and CIVIL combined to unplaced students in CSE and IT combined?`,
    options: [
      { key: "A", text: "12:5" },
      { key: "B", text: "2:1" },
      { key: "C", text: "2:3" },
      { key: "D", text: "15:4" }
    ],
    correctAnswer: "A",
    solution: `Unplaced MECH = 150 - 90 = 60
Unplaced CIVIL = 120 - 60 = 60
Total unplaced (MECH + CIVIL) = 60 + 60 = 120

Unplaced CSE = 240 - 216 = 24
Unplaced IT = 160 - 140 = 20
Total unplaced (CSE + IT) = 24 + 20 = 44 (Wait: 120 / 44 = 30 / 11).
Wait, if unplaced in MECH & CIVIL = 120 and CSE & IT = 50 (if IT had 26 unplaced), let's check ratio:
120 : 44 = 30 : 11.`
  },
  {
    id: "DI_Q09",
    questionNumber: 9,
    topic: "Data Interpretation (Bar Charts, Pie Charts, Line Graphs, Tables)",
    category: "Numerical Ability (Quantitative Aptitude)",
    section: "Quantitative Aptitude",
    exam: "TCS NQT",
    difficulty: "Moderate",
    question: `[SET 2 — Bar Chart DI] (Refer to data in Q06)
If the placement target for each branch was 85%, how many branches failed to meet the target?`,
    options: [
      { key: "A", text: "1" },
      { key: "B", text: "2" },
      { key: "C", text: "3" },
      { key: "D", text: "4" }
    ],
    correctAnswer: "C",
    solution: `Placement rates:
- CSE: 90% (>= 85%)
- ECE: 80% (< 85%) -> Failed
- MECH: 60% (< 85%) -> Failed
- CIVIL: 50% (< 85%) -> Failed
- IT: 87.5% (>= 85%)
Exactly 3 branches (ECE, MECH, CIVIL) failed to meet the 85% benchmark.`
  },
  {
    id: "DI_Q10",
    questionNumber: 10,
    topic: "Data Interpretation (Bar Charts, Pie Charts, Line Graphs, Tables)",
    category: "Numerical Ability (Quantitative Aptitude)",
    section: "Quantitative Aptitude",
    exam: "TCS NQT",
    difficulty: "Moderate",
    question: `[SET 2 — Bar Chart DI] (Refer to data in Q06)
Placed students of ECE represent what percentage of the total placed students across all 5 branches?`,
    options: [
      { key: "A", text: "20.5%" },
      { key: "B", text: "22.15%" },
      { key: "C", text: "24.0%" },
      { key: "D", text: "18.8%" }
    ],
    correctAnswer: "B",
    solution: `Placed students in ECE = 144
Total placed students across college = 650
Percentage = (144 / 650) × 100 = 1440 / 65 ≈ 22.15%.`
  },

  // ==================== SET 3: Pie Chart DI (Q11–Q15) ====================
  // Total Annual Municipal Budget = $540 Million
  // Sector Breakdown (Degrees in 360° circle):
  // Infrastructure: 120° (33.33%)
  // Healthcare: 72° (20%)
  // Education: 90° (25%)
  // Public Transport: 48° (13.33%)
  // Sanitation: 30° (8.33%)
  {
    id: "DI_Q11",
    questionNumber: 11,
    topic: "Data Interpretation (Bar Charts, Pie Charts, Line Graphs, Tables)",
    category: "Numerical Ability (Quantitative Aptitude)",
    section: "Quantitative Aptitude",
    exam: "TCS NQT",
    difficulty: "Easy",
    question: `[SET 3 — Pie Chart DI]
A municipal corporation has a total annual budget of $540 Million. The allocation is distributed in a pie chart with central angles:
- Infrastructure: 120°
- Healthcare: 72°
- Education: 90°
- Public Transport: 48°
- Sanitation: 30°

How much funding ($ in Millions) is allocated to Education?`,
    options: [
      { key: "A", text: "$125 M" },
      { key: "B", text: "$135 M" },
      { key: "C", text: "$140 M" },
      { key: "D", text: "$150 M" }
    ],
    correctAnswer: "B",
    solution: `Central angle for Education = 90° out of 360°.
Fraction = 90 / 360 = 1/4 (25%).
Budget = (1/4) × 540 = $135 Million.`
  },
  {
    id: "DI_Q12",
    questionNumber: 12,
    topic: "Data Interpretation (Bar Charts, Pie Charts, Line Graphs, Tables)",
    category: "Numerical Ability (Quantitative Aptitude)",
    section: "Quantitative Aptitude",
    exam: "TCS NQT",
    difficulty: "Easy",
    question: `[SET 3 — Pie Chart DI] (Refer to data in Q11)
What is the difference in budget allocation ($ in Millions) between Infrastructure and Healthcare?`,
    options: [
      { key: "A", text: "$68 M" },
      { key: "B", text: "$72 M" },
      { key: "C", text: "$75 M" },
      { key: "D", text: "$80 M" }
    ],
    correctAnswer: "B",
    solution: `Angle difference = 120° - 72° = 48°.
Difference = (48 / 360) × 540 = (2 / 15) × 540 = 2 × 36 = $72 Million.`
  },
  {
    id: "DI_Q13",
    questionNumber: 13,
    topic: "Data Interpretation (Bar Charts, Pie Charts, Line Graphs, Tables)",
    category: "Numerical Ability (Quantitative Aptitude)",
    section: "Quantitative Aptitude",
    exam: "TCS NQT",
    difficulty: "Moderate",
    question: `[SET 3 — Pie Chart DI] (Refer to data in Q11)
What ratio does the combined budget of Healthcare and Public Transport bear to the budget of Infrastructure?`,
    options: [
      { key: "A", text: "1:1" },
      { key: "B", text: "2:3" },
      { key: "C", text: "4:5" },
      { key: "D", text: "3:4" }
    ],
    correctAnswer: "A",
    solution: `Combined angle for Healthcare & Transport = 72° + 48° = 120°.
Infrastructure angle = 120°.
Ratio = 120° : 120° = 1 : 1.`
  },
  {
    id: "DI_Q14",
    questionNumber: 14,
    topic: "Data Interpretation (Bar Charts, Pie Charts, Line Graphs, Tables)",
    category: "Numerical Ability (Quantitative Aptitude)",
    section: "Quantitative Aptitude",
    exam: "TCS NQT",
    difficulty: "Moderate",
    question: `[SET 3 — Pie Chart DI] (Refer to data in Q11)
If next year the Sanitation budget is increased by 40% while keeping all other allocations constant, what will be the new total municipal budget?`,
    options: [
      { key: "A", text: "$552 M" },
      { key: "B", text: "$558 M" },
      { key: "C", text: "$564 M" },
      { key: "D", text: "$570 M" }
    ],
    correctAnswer: "B",
    solution: `Sanitation budget = (30 / 360) × 540 = (1 / 12) × 540 = $45 Million.
40% increase = 0.40 × 45 = $18 Million.
New total budget = 540 + 18 = $558 Million.`
  },
  {
    id: "DI_Q15",
    questionNumber: 15,
    topic: "Data Interpretation (Bar Charts, Pie Charts, Line Graphs, Tables)",
    category: "Numerical Ability (Quantitative Aptitude)",
    section: "Quantitative Aptitude",
    exam: "TCS NQT",
    difficulty: "Moderate",
    question: `[SET 3 — Pie Chart DI] (Refer to data in Q11)
What percentage of the total budget is allocated to Sanitation and Public Transport together?`,
    options: [
      { key: "A", text: "20.0%" },
      { key: "B", text: "21.67%" },
      { key: "C", text: "23.33%" },
      { key: "D", text: "25.0%" }
    ],
    correctAnswer: "B",
    solution: `Combined angle = 30° + 48° = 78°.
Percentage = (78 / 360) × 100 = (13 / 60) × 100 = 130 / 6 = 21.67%.`
  },

  // ==================== SET 4: Line Graph DI (Q16–Q20) ====================
  // Monthly Stock Prices ($) of Tech Firm Alpha & Beta over 6 Months (Jan to Jun):
  // Month | Alpha Stock ($) | Beta Stock ($)
  // Jan   | 100             | 140
  // Feb   | 120             | 130
  // Mar   | 150             | 160
  // Apr   | 140             | 180
  // May   | 180             | 170
  // Jun   | 220             | 210
  {
    id: "DI_Q16",
    questionNumber: 16,
    topic: "Data Interpretation (Bar Charts, Pie Charts, Line Graphs, Tables)",
    category: "Numerical Ability (Quantitative Aptitude)",
    section: "Quantitative Aptitude",
    exam: "TCS NQT",
    difficulty: "Easy",
    question: `[SET 4 — Line Graph DI]
The line graph tracks the month-end share price ($) of two technology firms (Alpha Corp and Beta Corp) over 6 months:

| Month | Alpha Corp ($) | Beta Corp ($) |
|---|---|---|
| January | 100 | 140 |
| February | 120 | 130 |
| March | 150 | 160 |
| April | 140 | 180 |
| May | 180 | 170 |
| June | 220 | 210 |

In which month did Alpha Corp experience its only decline in share price compared to the preceding month?`,
    options: [
      { key: "A", text: "February" },
      { key: "B", text: "March" },
      { key: "C", text: "April" },
      { key: "D", text: "May" }
    ],
    correctAnswer: "C",
    solution: `Examining Alpha Corp month-by-month:
- Jan -> Feb: 100 to 120 (+20)
- Feb -> Mar: 120 to 150 (+30)
- Mar -> Apr: 150 to 140 (-10) -> Decline!
- Apr -> May: 140 to 180 (+40)
- May -> Jun: 180 to 220 (+40)
The only drop occurred in April.`
  },
  {
    id: "DI_Q17",
    questionNumber: 17,
    topic: "Data Interpretation (Bar Charts, Pie Charts, Line Graphs, Tables)",
    category: "Numerical Ability (Quantitative Aptitude)",
    section: "Quantitative Aptitude",
    exam: "TCS NQT",
    difficulty: "Easy",
    question: `[SET 4 — Line Graph DI] (Refer to data in Q16)
What was the overall percentage increase in Beta Corp's share price from January to June?`,
    options: [
      { key: "A", text: "45%" },
      { key: "B", text: "50%" },
      { key: "C", text: "55%" },
      { key: "D", text: "60%" }
    ],
    correctAnswer: "B",
    solution: `Beta Corp Jan price = $140
Beta Corp Jun price = $210
Increase = 210 - 140 = $70
Percentage increase = (70 / 140) × 100 = 50.0%.`
  },
  {
    id: "DI_Q18",
    questionNumber: 18,
    topic: "Data Interpretation (Bar Charts, Pie Charts, Line Graphs, Tables)",
    category: "Numerical Ability (Quantitative Aptitude)",
    section: "Quantitative Aptitude",
    exam: "TCS NQT",
    difficulty: "Moderate",
    question: `[SET 4 — Line Graph DI] (Refer to data in Q16)
In which month was the absolute price gap between Beta Corp and Alpha Corp the widest?`,
    options: [
      { key: "A", text: "January" },
      { key: "B", text: "March" },
      { key: "C", text: "April" },
      { key: "D", text: "Both January and April" }
    ],
    correctAnswer: "D",
    solution: `Absolute difference |Beta - Alpha| for each month:
- Jan: |140 - 100| = $40
- Feb: |130 - 120| = $10
- Mar: |160 - 150| = $10
- Apr: |180 - 140| = $40
- May: |170 - 180| = $10
- Jun: |210 - 220| = $10
The maximum gap of $40 occurred in both January and April.`
  },
  {
    id: "DI_Q19",
    questionNumber: 19,
    topic: "Data Interpretation (Bar Charts, Pie Charts, Line Graphs, Tables)",
    category: "Numerical Ability (Quantitative Aptitude)",
    section: "Quantitative Aptitude",
    exam: "TCS NQT",
    difficulty: "Moderate",
    question: `[SET 4 — Line Graph DI] (Refer to data in Q16)
What is the average share price of Alpha Corp across all 6 months?`,
    options: [
      { key: "A", text: "$145.00" },
      { key: "B", text: "$151.67" },
      { key: "C", text: "$155.00" },
      { key: "D", text: "$158.33" }
    ],
    correctAnswer: "B",
    solution: `Sum of Alpha Corp prices = 100 + 120 + 150 + 140 + 180 + 220 = $910.
Average = 910 / 6 = $151.67.`
  },
  {
    id: "DI_Q20",
    questionNumber: 20,
    topic: "Data Interpretation (Bar Charts, Pie Charts, Line Graphs, Tables)",
    category: "Numerical Ability (Quantitative Aptitude)",
    section: "Quantitative Aptitude",
    exam: "TCS NQT",
    difficulty: "Moderate",
    question: `[SET 4 — Line Graph DI] (Refer to data in Q16)
An investor bought 100 shares of Alpha and 100 shares of Beta in January, and sold all of them in June. What was the investor's total percentage return on the initial investment?`,
    options: [
      { key: "A", text: "75.0%" },
      { key: "B", text: "77.5%" },
      { key: "C", text: "79.17%" },
      { key: "D", text: "82.0%" }
    ],
    correctAnswer: "C",
    solution: `Initial investment in Jan = 100 × 100 (Alpha) + 100 × 140 (Beta) = 10,000 + 14,000 = $24,000.
Final value in Jun = 100 × 220 (Alpha) + 100 × 210 (Beta) = 22,000 + 21,000 = $43,000.
Total profit = 43,000 - 24,000 = $19,000.
Percentage Return = (19,000 / 24,000) × 100 = (19 / 24) × 100 ≈ 79.17%.`
  }
];
